#!/bin/sh

################################################################################
# build
#
# This hook is responsible for running a full "build" of the project for the 
# purpose of Continuus Integration
#
################################################################################

echo 'OH NOES!!!!'
echo 'Run for your lives!' >2

exit 1
