#!/usr/bin/env ruby

################################################################################
# notify
#
# This hook is reponsible for notifying the user of the results of a task, such
# as a Continuous Integration build.
#
# PARAMETERS:
#
# This hook will be called with the form:
#
#   .devver/hooks/notify TASK EXIT_STATUS
#
# * TASK is the name of the task that triggered the notification
# * EXIT_STATUS is the numeric exit status of the task. 0 indicates success.
#
# INPUT:
#
# This hook will be provided with a transcript of the triggering task's output.
# Both STDOUT and STDERR output will be included in the transcript.
#
# OUTPUT:
#
# This task should exit with a 0 status if the notification was successful, and
# a nonzero status if the notification failed.
#
################################################################################
require 'fileutils'

local_filename = File.join('/tmp','devver_build_notify_ci_api_sample')

File.open(local_filename, 'w') {|f| f.write("output: #{$stdin.read}") }
FileUtils.chmod(0666, local_filename)

exit 1